[package]
name = "deno_num_cpus"
version = "0.1.5"
authors = ["迷渡 <justjavac@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = "0.54.0"
actix-rt = "1.0"
actix-web = "2.0"
futures = "0.3.5"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"